name: Test
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [15.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install node dependencies
        run: npm install
        
      - name: Transpile code
        run: npm run transpile

      - name: Run tests with coverage
        run: npm run cover
        
      - name: Send coverage report to Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Send coverage report to Codecov
        uses: Atrox/codecov-action@v0.1.2
        env: 
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}